### ISSUE TITLE
--performance-tier is not a valid option

### ISSUE THREAD

**Issue by iver56** [Azure/azure-postgresql#15]
The `az postgres server create` example in the following document does not work:
https://github.com/Azure/azure-postgresql/blob/master/samples/django-python/0.md#create-an-azure-postgresql-database-server

The error one gets indicates that the `--performance-tier` option is not valid. It may have been valid earlier, I guess.

Client: az v2.0.19 on mac

**Comment by eflamm** [comment]
I'm not sure it's helpful for me to comment, but it appears that several parameters have been changed since this walkthrough was published: `az postgres server create` now accepts a `--sku-name` parameter which combines tier/compute/scale - for example `--sku-name GP_Gen4_2`

**Comment by rachel-msft** [comment]
Thank you for your feedback. An update has been made.
