### ISSUE TITLE
Security vulnerability in 10.5, upgrade to 10.6

### ISSUE THREAD

**Issue by ahofman** [Azure/azure-postgresql#27]
Hi,

PostgreSQL 10.x versions have a disclosed security vulnerability that was fixed in PostgreSQL 10.6 according to https://www.postgresql.org/about/news/1905/. 

We see the PostgreSQL version in Azure is still 10.5. When can we expect our 10.x servers to be upgraded to 10.6 to close the security hole? 

Thanks

**Comment by rachel-msft** [comment]
Azure Database for PostgreSQL version 10 is currently on 10.7
