### ISSUE TITLE
Include bloat queries to health check notebook

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/azure-postgresql#43]
Will it be possible to include the queries from https://github.com/pgexperts/pgx_scripts/tree/master/bloat to the notebook?

**Comment by rachel-msft** [comment]
Hi Senthuran. The notebook here https://github.com/Azure/azure-postgresql/blob/master/samples/Health%20Checks/Postgres_database_health_check_notebook.ipynb is an example of what anyone can go create for themselves in Azure Data Studio. This notebook is based on the health check blog: https://www.citusdata.com/blog/2019/03/29/health-checks-for-your-postgres-database/ and so those are the queries it has.
