### ISSUE TITLE
Cannot Put the Read Replica in different resource group to master server

### ISSUE THREAD

**Issue by archmangler** [Azure/azure-postgresql#57]
It appears that it's not possible to create  a read replica in a different resource group to the master postgres instance.

This is unfortunate because it reduces the resilience of the postgres deployment: if the resource group is accidentally deleted we lose both the primary postgres server and the read replicas at one time.

Is this correct? If not , how can a read replica be deployed in a separate resource group and region to the primary?

**Comment by ramnov** [comment]
You can create the replica and then use the [Move](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-move-resources#use-the-portal) button in resource group level to move a replica to another resource group

**Comment by rachel-msft** [comment]
You can also use a resource lock to prevent accidental deletion of resources https://docs.microsoft.com/azure/azure-resource-manager/resource-group-lock-resources
